name: Check flake (run tests)

on:
  push:

jobs:
  check:
    strategy:
      max-parallel: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'master'
      - uses: cachix/install-nix-action@v31
        with:
          # explicitly enable sandbox
          extra_nix_config: sandbox = true
      - run: nix flake check
